# Generated by Django 3.1.4 on 2021-01-06 19:27

from django.conf import settings
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("rss_feeds", "0001_initial"),
    ]

    operations = []
