# Generated by Django 3.1.10 on 2022-05-17 13:35

from django.conf import settings
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("rss_feeds", "0002_remove_mongo_types"),
    ]

    operations = []
